// Generated by CoffeeScript 1.6.3
(function() {
  var Control, Element, draw, exports;

  Element = require('./Element');

  module.exports = exports = Control = Element.extend({
    name: 'Control',
    properties: {
      draw: draw = function(c) {
        return this.inner(draw, c);
      },
      position: null,
      size: null
    }
  });

}).call(this);
