// Generated by CoffeeScript 1.6.3
(function() {
  Object.merge(exports, {
    isNode: function(a) {
      return (a != null ? a.nodeName : void 0) != null;
    },
    isElement: function(a) {
      return (a != null ? a.tagName : void 0) != null;
    },
    createElement: (function() {
      var creator, _ref;
      if (((_ref = global.document) != null ? _ref.createElement : void 0) != null) {
        creator = global.document.createElement('div');
        return function(html) {
          var element;
          if (html.isId()) {
            return global.document.createElement(html);
          }
          creator.innerHTML = html;
          element = creator.firstChild;
          if (element != null) {
            creator.removeChild(element);
          }
          return element;
        };
      } else {
        return function() {
          throw new Error("Can't create elements without document");
        };
      }
    })()
  });

  exports.test = (function() {
    var assert;
    assert = require('chai').assert;
    if (global.window != null) {
      return {
        'createElement': {
          'creates with correct tag, attributes and children': function() {
            var element;
            element = exports.createElement('<div id="test">Test</div>');
            assert.equal(element.tagName, 'DIV');
            assert.equal(element.getAttribute('id'), 'test');
            return assert.equal(element.innerHTML, 'Test');
          }
        }
      };
    }
  })();

}).call(this);
