// Generated by CoffeeScript 1.6.2
(function() {
  var Enum, exports, key, value, webglConstants, _ref;

  Enum = require('../../Enum');

  module.exports = exports = {};

  Object.merge(exports, require('gl-matrix'));

  _ref = webglConstants = require('./constants');
  for (key in _ref) {
    value = _ref[key];
    exports[key] = new Enum(key, value);
  }

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
