// Generated by CoffeeScript 1.6.3
(function() {
  var Enum;

  module.exports = Enum = (function() {
    function Enum(name, value) {
      this.name = name;
      this.value = value;
    }

    Enum.prototype.toString = function() {
      return this.name;
    };

    Enum.prototype.valueOf = function() {
      return this.value;
    };

    return Enum;

  })();

}).call(this);

/*
//@ sourceMappingURL=Enum.map
*/
