// Generated by CoffeeScript 1.6.3
(function() {
  var exports, global, _base;

  require('sugar');

  global = (function() {
    return this;
  })();

  if (global.global == null) {
    global.global = global;
  }

  module.exports = exports = global;

  if (global.process == null) {
    global.process = {};
  }

  if ((_base = global.process).nextTick == null) {
    _base.nextTick = function(fn) {
      return setTimeout(fn, 0);
    };
  }

  if (global.Float32Array == null) {
    global.Float32Array = Array;
  }

}).call(this);

/*
//@ sourceMappingURL=global.map
*/
