// Generated by CoffeeScript 1.6.3
(function() {
  Object.merge(String.prototype, {
    isId: function() {
      return /^[^\d\W]\w*$/.test(this);
    }
  });

  exports.test = (function() {
    var assert;
    assert = require('chai').assert;
    return {
      '#isId': {
        "should match foo": function() {
          return assert("foo".isId());
        },
        "should not match <foo>": function() {
          return assert(!"<foo>".isId());
        },
        "should not match 2foo": function() {
          return assert(!"2foo".isId());
        }
      }
    };
  })();

}).call(this);
