// Generated by CoffeeScript 1.6.2
(function() {
  var global, _ref;

  require('sugar');

  global = (function() {
    return this;
  })();

  if ((_ref = global.global) == null) {
    global.global = global;
  }

}).call(this);

/*
//@ sourceMappingURL=global.map
*/
