// Generated by CoffeeScript 1.6.2
(function() {
  var exports;

  require('./global');

  global.glass = module.exports = exports = {
    Component: require('./Component'),
    Enum: require('./Enum'),
    patch: require('./patch'),
    ui: require('./ui')
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
