// Generated by CoffeeScript 1.6.3
(function() {
  var Canvas, exports, htmlControl;

  htmlControl = require('../html/Control');

  Canvas = module.exports = exports = htmlControl.extend({
    id: 'glass.ui.webgl.Canvas',
    properties: {
      element: '<canvas width="500" height="500" style="background:red"></canvas>'
    }
  });

}).call(this);

/*
//@ sourceMappingURL=Canvas.map
*/
