// Generated by CoffeeScript 1.6.3
(function() {
  var Enum, key, value, webglConstants, _ref;

  Enum = require('../../Enum');

  _ref = webglConstants = require('./constants');
  for (key in _ref) {
    value = _ref[key];
    exports[key] = new Enum(key, value);
  }

}).call(this);
