// Generated by CoffeeScript 1.6.2
(function() {
  var exports;

  module.exports = exports = {
    canvas: {},
    html: {},
    webgl: require('./webgl')
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
